<a href="https://colab.research.google.com/github/cth127/cth127.github.io/blob/master/Porto_Seguro%E2%80%99s_Safe_Driver_Prediction_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
%matplotlib inline

os.chdir("./drive/My Drive/Colab Notebooks/data")

In [0]:
os.chdir('./캐글스터디 포르토')

In [0]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [0]:
train = train.replace(-1, np.nan)
test = test.replace(-1, np.nan)

# EDA

In [0]:
# Let's look at the data

train.head()

   id  target  ps_ind_01  ...  ps_calc_18_bin  ps_calc_19_bin  ps_calc_20_bin
0   7       0          2  ...               0               0               1
1   9       0          1  ...               0               1               0
2  13       0          5  ...               0               1               0
3  16       0          0  ...               0               0               0
4  17       0          0  ...               1               1               0

[5 rows x 59 columns]

In [0]:
train.isna().sum()

id                     0
target                 0
ps_ind_01              0
ps_ind_02_cat        216
ps_ind_03              0
ps_ind_04_cat         83
ps_ind_05_cat       5809
ps_ind_06_bin          0
ps_ind_07_bin          0
ps_ind_08_bin          0
ps_ind_09_bin          0
ps_ind_10_bin          0
ps_ind_11_bin          0
ps_ind_12_bin          0
ps_ind_13_bin          0
ps_ind_14              0
ps_ind_15              0
ps_ind_16_bin          0
ps_ind_17_bin          0
ps_ind_18_bin          0
ps_reg_01              0
ps_reg_02              0
ps_reg_03         107772
ps_car_01_cat        107
ps_car_02_cat          5
ps_car_03_cat     411231
ps_car_04_cat          0
ps_car_05_cat     266551
ps_car_06_cat          0
ps_car_07_cat      11489
ps_car_08_cat          0
ps_car_09_cat        569
ps_car_10_cat          0
ps_car_11_cat          0
ps_car_11              5
ps_car_12              1
ps_car_13              0
ps_car_14          42620
ps_car_15              0
ps_calc_01             0
ps_calc_02             0
ps_calc_03             0
ps_calc_04             0
ps_calc_05             0
ps_calc_06             0
ps_calc_07             0
ps_calc_08             0
ps_calc_09             0
ps_calc_10             0
ps_calc_11             0
ps_calc_12             0
ps_calc_13             0
ps_calc_14             0
ps_calc_15_bin         0
ps_calc_16_bin         0
ps_calc_17_bin         0
ps_calc_18_bin         0
ps_calc_19_bin         0
ps_calc_20_bin         0
dtype: int64

In [0]:
test.isna().sum()

id                     0
ps_ind_01              0
ps_ind_02_cat        307
ps_ind_03              0
ps_ind_04_cat        145
ps_ind_05_cat       8710
ps_ind_06_bin          0
ps_ind_07_bin          0
ps_ind_08_bin          0
ps_ind_09_bin          0
ps_ind_10_bin          0
ps_ind_11_bin          0
ps_ind_12_bin          0
ps_ind_13_bin          0
ps_ind_14              0
ps_ind_15              0
ps_ind_16_bin          0
ps_ind_17_bin          0
ps_ind_18_bin          0
ps_reg_01              0
ps_reg_02              0
ps_reg_03         161684
ps_car_01_cat        160
ps_car_02_cat          5
ps_car_03_cat     616911
ps_car_04_cat          0
ps_car_05_cat     400359
ps_car_06_cat          0
ps_car_07_cat      17331
ps_car_08_cat          0
ps_car_09_cat        877
ps_car_10_cat          0
ps_car_11_cat          0
ps_car_11              1
ps_car_12              0
ps_car_13              0
ps_car_14          63805
ps_car_15              0
ps_calc_01             0
ps_calc_02             0
ps_calc_03             0
ps_calc_04             0
ps_calc_05             0
ps_calc_06             0
ps_calc_07             0
ps_calc_08             0
ps_calc_09             0
ps_calc_10             0
ps_calc_11             0
ps_calc_12             0
ps_calc_13             0
ps_calc_14             0
ps_calc_15_bin         0
ps_calc_16_bin         0
ps_calc_17_bin         0
ps_calc_18_bin         0
ps_calc_19_bin         0
ps_calc_20_bin         0
dtype: int64

In [0]:
var_list = train.columns.tolist()[2:]

In [0]:
for i in var_list :
  if test[i].isna().sum() > 0 :
    train.drop(columns = [i], inplace = True)
    test.drop(columns = [i], inplace = True)

In [0]:
var_list = train.columns.tolist()[2:]

In [0]:
for i in var_list :
  print(len(train[i].unique()))

8
12
2
2
2
2
2
2
2
2
5
14
2
2
2
10
19
10
18
2
3
104
184
70482
15
10
10
10
6
7
11
10
11
8
26
20
11
14
24
2
2
2
2
2
2

In [0]:
des_list = []
real_list = []
for i in var_list :
  if len(train[i].unique()) < 105 :
    des_list.append(i)
  else :
    real_list.append(i)

In [0]:
print(des_list)
print(real_list)

['ps_ind_01', 'ps_ind_03', 'ps_ind_06_bin', 'ps_ind_07_bin', 'ps_ind_08_bin', 'ps_ind_09_bin', 'ps_ind_10_bin', 'ps_ind_11_bin', 'ps_ind_12_bin', 'ps_ind_13_bin', 'ps_ind_14', 'ps_ind_15', 'ps_ind_16_bin', 'ps_ind_17_bin', 'ps_ind_18_bin', 'ps_reg_01', 'ps_reg_02', 'ps_car_04_cat', 'ps_car_06_cat', 'ps_car_08_cat', 'ps_car_10_cat', 'ps_car_11_cat', 'ps_car_15', 'ps_calc_01', 'ps_calc_02', 'ps_calc_03', 'ps_calc_04', 'ps_calc_05', 'ps_calc_06', 'ps_calc_07', 'ps_calc_08', 'ps_calc_09', 'ps_calc_10', 'ps_calc_11', 'ps_calc_12', 'ps_calc_13', 'ps_calc_14', 'ps_calc_15_bin', 'ps_calc_16_bin', 'ps_calc_17_bin', 'ps_calc_18_bin', 'ps_calc_19_bin', 'ps_calc_20_bin']
['ps_car_12', 'ps_car_13']

In [0]:
for i in des_list :
  print(pd.crosstab(index = train['target'], columns = train[i]))

ps_ind_01       0       1      2      3      4      5      6      7
target
0          181362  139142  79428  49096  32011  58986  16919  16574
1            6232    4842   3040   2097   1513   2478    763    729
ps_ind_03     0      1      2      3      4   ...     7      8      9      10     11
target                                        ...
0          14539  65469  93194  79550  64984  ...  50195  38122  24536  13897  10786
1            975   2525   2916   2423   2229  ...   2169   1545    900    587    462

[2 rows x 12 columns]
ps_ind_06_bin       0       1
target
0              345846  227672
1               15006    6688
ps_ind_07_bin       0       1
target
0              427773  145745
1               14450    7244
ps_ind_08_bin       0      1
target
0              480049  93469
1               17595   4099
ps_ind_09_bin       0       1
target
0              466886  106632
1               18031    3663
ps_ind_10_bin       0    1
target
0              573308  210
1               21682   12
ps_ind_11_bin       0    1
target
0              572557  961
1               21648   46
ps_ind_12_bin       0     1
target
0              568189  5329
1               21405   289
ps_ind_13_bin       0    1
target
0              572983  535
1               21665   29
ps_ind_14       0     1    2    3  4
target
0          567457  5222  708  127  4
1           21375   273   36    9  1
ps_ind_15     0      1      2      3      4   ...     9      10     11     12     13
target                                        ...
0          30464  11082  17836  31015  40141  ...  44090  52463  51593  43474  34168
1           1362    535    839   1252   1629  ...   1407   1878   1622   1377   1088

[2 rows x 14 columns]
ps_ind_16_bin       0       1
target
0              193057  380461
1                8825   12869
ps_ind_17_bin       0      1
target
0              505424  68094
1               17719   3975
ps_ind_18_bin       0      1
target
0              485697  87821
1               18182   3512
ps_reg_01    0.0    0.1    0.2    0.3  ...    0.6    0.7    0.8     0.9
target                                 ...
0          20831  42163  24427  39004  ...  54208  65275  57953  186603
1            851   1029    686   1286  ...   2035   2622   2324    8005

[2 rows x 10 columns]
ps_reg_02    0.0    0.1     0.2    0.3    0.4  ...   1.4   1.5   1.6   1.7   1.8
target                                         ...
0          86281  31043  111554  91825  57564  ...  6548  5582  4808  2338  4439
1           3016    773    3332   3208   2182  ...   329   263   287   140   298

[2 rows x 19 columns]
ps_car_04_cat       0      1      2    3    4    5     6    7      8      9
target
0              479970  30547  22648  607  225  506  1468  126  19565  17856
1               16611   1568   1122   33    5   39    92   13   1033   1178
ps_car_06_cat      0       1     2      3   ...     14     15    16    17
target                                      ...
0              106735  114339  1501  11539  ...  57221  20621  4375  4620
1                3685    4047   106    458  ...   2032   1111   207   315

[2 rows x 18 columns]
ps_car_08_cat      0       1
target
0              95457  478061
1               4491   17203
ps_car_10_cat     0       1    2
target
0              4690  568659  169
1               167   21520    7
ps_car_11_cat   1     2     3     4      5    ...   100   101   102    103    104
target                                        ...
0              3196  2456  3022  1499  11988  ...  4212  7058  2032  23615  81253
1               135    97   163    97    525  ...   233   281    71    647   3830

[2 rows x 104 columns]
ps_car_15  0.000000  1.000000  1.414214  ...  3.464102  3.605551  3.741657
target                                   ...
0             13844      6540      6358  ...     74140    104892     55442
1               342       168       157  ...      3060      4873      2315

[2 rows x 15 columns]
ps_calc_01    0.0    0.1    0.2    0.3  ...    0.6    0.7    0.8    0.9
target                                  ...
0           57620  57422  57372  57186  ...  57706  57321  57595  56871
1            2160   2082   2141   2191  ...   2131   2224   2115   2215

[2 rows x 10 columns]
ps_calc_02    0.0    0.1    0.2    0.3  ...    0.6    0.7    0.8    0.9
target                                  ...
0           57534  57255  57191  57421  ...  57272  57339  56938  57090
1            2084   2128   2194   2172  ...   2229   2163   2180   2129

[2 rows x 10 columns]
ps_calc_03    0.0    0.1    0.2    0.3  ...    0.6    0.7    0.8    0.9
target                                  ...
0           57238  57892  56968  57602  ...  57363  57250  57277  57245
1            2080   2144   2169   2217  ...   2158   2143   2232   2173

[2 rows x 10 columns]
ps_calc_04      0       1       2       3      4      5
target
0           23057  104085  186828  169158  76738  13652
1             855    3927    7149    6354   2868    541
ps_calc_05      0       1       2       3      4     5    6
target
0           59010  164640  188009  114900  39189  7242  528
1            2216    6220    7151    4292   1493   292   30
ps_calc_06  0   1    2     3     4   ...     6       7       8       9      10
target                               ...
0            1   6  129  1161  6448  ...  70804  134743  168497  124532  41542
1            0   0    3    38   257  ...   2674    5028    6518    4675   1543

[2 rows x 11 columns]
ps_calc_07      0      1       2       3       4      5      6     7    8   9
target
0           14735  66725  134040  156573  117542  59524  19627  4201  530  21
1             555   2584    5061    5841    4497   2181    776   180   17   2
ps_calc_08  2   3    4     5      6   ...     8       9       10     11     12
target                                ...
0           10  87  812  4299  16539  ...  99098  146263  145885  88263  24480
1            0   3   30   170    644  ...   3846    5483    5445   3376    912

[2 rows x 11 columns]
ps_calc_09      0       1       2       3      4      5     6    7
target
0           33210  117080  175794  147245  74121  22171  3643  254
1            1269    4311    6725    5584   2852    805   139    9
ps_calc_10   0     1     2      3      4      5   ...   20  21  22  23  24  25
target                                            ...
0           133  1071  4401  12508  26232  44522  ...  160  63  32  10   1   1
1             6    36   165    473    972   1659  ...    8   2   1   0   0   0

[2 rows x 26 columns]
ps_calc_11    0      1      2      3      4      5   ...   14   15  16  17  18  19
target                                               ...
0           2371  13500  36981  66913  90492  98874  ...  603  181  66  22  11   1
1             90    535   1383   2606   3398   3638  ...   28    8   2   0   0   0

[2 rows x 20 columns]
ps_calc_12      0       1       2      3      4     5     6    7   8   9   10
target
0           135818  195882  140000  67827  24860  7019  1658  377  63  11   3
1             5183    7398    5321   2524    918   271    66   10   3   0   0
ps_calc_13     0      1       2       3      4   ...    9    10  11  12  13
target                                           ...
0           32401  93153  134274  127597  92233  ...  1120  340  86  19   3
1            1257   3508    5060    4815   3520  ...    40   11   2   1   1

[2 rows x 14 columns]
ps_calc_14   0     1     2      3      4      5   ...   18   19  20  21  22  23
target                                            ...
0           298  2317  8620  22038  41062  61643  ...  296  123  46  18   5   1
1            12    81   322    787   1534   2386  ...    9    8   1   0   0   0

[2 rows x 24 columns]
ps_calc_15_bin       0      1
target
0               503286  70232
1                19056   2638
ps_calc_16_bin       0       1
target
0               213474  360044
1                 8040   13654
ps_calc_17_bin       0       1
target
0               255675  317843
1                 9681   12013
ps_calc_18_bin       0       1
target
0               408842  164676
1                15436    6258
ps_calc_19_bin       0       1
target
0               373254  200264
1                14215    7479
ps_calc_20_bin       0      1
target
0               485544  87974
1                18411   3283

In [0]:
# chi-square independence test

des_bad_list = []
des_good_list = []

import scipy as sp
for i in des_list :
  obs = np.array(pd.crosstab(index = train[i], columns = train['target']))
  pvalue = sp.stats.chi2_contingency(obs)[1]
  if pvalue > 0.05 :
    print("%s seems useless with p-value : %s" %(i, pvalue))
    des_bad_list.append(i)
  else :
    print("*****%s seems useless with p-value : %s*****" %(i, pvalue))
    des_good_list.append(i)

*****ps_ind_01 seems useless with p-value : 2.332355331937182e-51*****
*****ps_ind_03 seems useless with p-value : 1.892495882492183e-134*****
*****ps_ind_06_bin seems useless with p-value : 1.0076927225850892e-151*****
*****ps_ind_07_bin seems useless with p-value : 1.7232976057968082e-153*****
*****ps_ind_08_bin seems useless with p-value : 3.921476396601753e-24*****
*****ps_ind_09_bin seems useless with p-value : 2.2127034437970573e-10*****
ps_ind_10_bin seems useless with p-value : 0.22208630630633355
ps_ind_11_bin seems useless with p-value : 0.13871738717830912
*****ps_ind_12_bin seems useless with p-value : 2.0998818420361575e-09*****
ps_ind_13_bin seems useless with p-value : 0.07414551103659972
*****ps_ind_14 seems useless with p-value : 1.1120266226289703e-07*****
*****ps_ind_15 seems useless with p-value : 1.3698907030656262e-63*****
*****ps_ind_16_bin seems useless with p-value : 8.073342449313144e-102*****
*****ps_ind_17_bin seems useless with p-value : 1.355511031736427e-179*****
*****ps_ind_18_bin seems useless with p-value : 0.0004567134977460295*****
*****ps_reg_01 seems useless with p-value : 4.002503339150603e-92*****
*****ps_reg_02 seems useless with p-value : 7.928385557232815e-181*****
*****ps_car_04_cat seems useless with p-value : 1.0412615245598996e-180*****
*****ps_car_06_cat seems useless with p-value : 8.852999916422575e-166*****
*****ps_car_08_cat seems useless with p-value : 1.9293600562947464e-55*****
ps_car_10_cat seems useless with p-value : 0.7228978253269899
*****ps_car_11_cat seems useless with p-value : 1.4634402224814853e-244*****
*****ps_car_15 seems useless with p-value : 3.276968742125271e-117*****
ps_calc_01 seems useless with p-value : 0.11843459724304878
ps_calc_02 seems useless with p-value : 0.3289097185298593
ps_calc_03 seems useless with p-value : 0.5861691547004345
ps_calc_04 seems useless with p-value : 0.6855214840277815
ps_calc_05 seems useless with p-value : 0.32403182697909916
ps_calc_06 seems useless with p-value : 0.6892777239065774
ps_calc_07 seems useless with p-value : 0.24655542162439836
ps_calc_08 seems useless with p-value : 0.8199865099573519
ps_calc_09 seems useless with p-value : 0.5222653462539589
ps_calc_10 seems useless with p-value : 0.5184191072780804
ps_calc_11 seems useless with p-value : 0.5005050319838356
ps_calc_12 seems useless with p-value : 0.9524454391477332
ps_calc_13 seems useless with p-value : 0.8076907178195655
ps_calc_14 seems useless with p-value : 0.8943920573686647
ps_calc_15_bin seems useless with p-value : 0.7130137900732124
ps_calc_16_bin seems useless with p-value : 0.6354080551735378
ps_calc_17_bin seems useless with p-value : 0.9010806852088695
ps_calc_18_bin seems useless with p-value : 0.6755376371151457
ps_calc_19_bin seems useless with p-value : 0.1808603146226591
ps_calc_20_bin seems useless with p-value : 0.413571052217771

In [0]:
print(len(des_good_list), len(des_bad_list))

19 24

In [0]:
# ANOVA with real-valued variables

import statsmodels.api as sm
from statsmodels.formula.api import ols
  
for i in real_list :
  lm1=ols("%s ~ C(target)" %(i), data = train).fit()
  table = sm.stats.anova_lm(lm1, typ=2)
  print(table)

                sum_sq        df           F         PR(>F)
C(target)     3.045595       1.0  897.418475  5.013042e-197
Residual   2019.978046  595209.0         NaN            NaN
                 sum_sq        df            F  PR(>F)
C(target)     87.217228       1.0  1734.169631     0.0
Residual   29935.114323  595210.0          NaN     NaN

In [0]:
# we'll do one-hot with des_good_list
full = pd.concat([train, test], axis = 0)
full_2 = pd.get_dummies(full, prefix=des_good_list, columns = des_good_list)
for i in des_bad_list :
  full_2.drop(columns = [i], inplace = True)  
train = full_2.iloc[0 :len(train)]
test = full_2.iloc[len(train) : ]
del full, full_2

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.

In [0]:
print(len(train), len(test))

595212 892816

In [0]:
test.head()

   id  ps_car_11_cat  ...  ps_car_15_3.6055512755  ps_car_15_3.7416573868
0   0             65  ...                       0                       0
1   1            103  ...                       0                       0
2   2             29  ...                       0                       0
3   3             40  ...                       0                       0
4   4            101  ...                       0                       0

[5 rows x 188 columns]

In [0]:
train.head()

   id  ps_car_11_cat  ...  ps_car_15_3.6055512755  ps_car_15_3.7416573868
0   7             12  ...                       1                       0
1   9             19  ...                       0                       0
2  13             60  ...                       0                       0
3  16            104  ...                       0                       0
4  17             82  ...                       0                       0

[5 rows x 188 columns]

In [0]:
train.shape

(595212, 237)

In [0]:
var_list = train.columns.tolist()
var_list.remove('target')
var_list.remove('id')
var_list

['ps_car_12',
 'ps_car_13',
 'ps_ind_01_0',
 'ps_ind_01_1',
 'ps_ind_01_2',
 'ps_ind_01_3',
 'ps_ind_01_4',
 'ps_ind_01_5',
 'ps_ind_01_6',
 'ps_ind_01_7',
 'ps_ind_03_0',
 'ps_ind_03_1',
 'ps_ind_03_2',
 'ps_ind_03_3',
 'ps_ind_03_4',
 'ps_ind_03_5',
 'ps_ind_03_6',
 'ps_ind_03_7',
 'ps_ind_03_8',
 'ps_ind_03_9',
 'ps_ind_03_10',
 'ps_ind_03_11',
 'ps_ind_06_bin_0',
 'ps_ind_06_bin_1',
 'ps_ind_07_bin_0',
 'ps_ind_07_bin_1',
 'ps_ind_08_bin_0',
 'ps_ind_08_bin_1',
 'ps_ind_09_bin_0',
 'ps_ind_09_bin_1',
 'ps_ind_12_bin_0',
 'ps_ind_12_bin_1',
 'ps_ind_14_0',
 'ps_ind_14_1',
 'ps_ind_14_2',
 'ps_ind_14_3',
 'ps_ind_14_4',
 'ps_ind_15_0',
 'ps_ind_15_1',
 'ps_ind_15_2',
 'ps_ind_15_3',
 'ps_ind_15_4',
 'ps_ind_15_5',
 'ps_ind_15_6',
 'ps_ind_15_7',
 'ps_ind_15_8',
 'ps_ind_15_9',
 'ps_ind_15_10',
 'ps_ind_15_11',
 'ps_ind_15_12',
 'ps_ind_15_13',
 'ps_ind_16_bin_0',
 'ps_ind_16_bin_1',
 'ps_ind_17_bin_0',
 'ps_ind_17_bin_1',
 'ps_ind_18_bin_0',
 'ps_ind_18_bin_1',
 'ps_reg_01_0.0',
 'ps_reg_01_0.1',
 'ps_reg_01_0.2',
 'ps_reg_01_0.3',
 'ps_reg_01_0.4',
 'ps_reg_01_0.5',
 'ps_reg_01_0.6',
 'ps_reg_01_0.7',
 'ps_reg_01_0.8',
 'ps_reg_01_0.9',
 'ps_reg_02_0.0',
 'ps_reg_02_0.1',
 'ps_reg_02_0.2',
 'ps_reg_02_0.3',
 'ps_reg_02_0.4',
 'ps_reg_02_0.5',
 'ps_reg_02_0.6',
 'ps_reg_02_0.7',
 'ps_reg_02_0.8',
 'ps_reg_02_0.9',
 'ps_reg_02_1.0',
 'ps_reg_02_1.1',
 'ps_reg_02_1.2',
 'ps_reg_02_1.3',
 'ps_reg_02_1.4',
 'ps_reg_02_1.5',
 'ps_reg_02_1.6',
 'ps_reg_02_1.7',
 'ps_reg_02_1.8',
 'ps_car_04_cat_0',
 'ps_car_04_cat_1',
 'ps_car_04_cat_2',
 'ps_car_04_cat_3',
 'ps_car_04_cat_4',
 'ps_car_04_cat_5',
 'ps_car_04_cat_6',
 'ps_car_04_cat_7',
 'ps_car_04_cat_8',
 'ps_car_04_cat_9',
 'ps_car_06_cat_0',
 'ps_car_06_cat_1',
 'ps_car_06_cat_2',
 'ps_car_06_cat_3',
 'ps_car_06_cat_4',
 'ps_car_06_cat_5',
 'ps_car_06_cat_6',
 'ps_car_06_cat_7',
 'ps_car_06_cat_8',
 'ps_car_06_cat_9',
 'ps_car_06_cat_10',
 'ps_car_06_cat_11',
 'ps_car_06_cat_12',
 'ps_car_06_cat_13',
 'ps_car_06_cat_14',
 'ps_car_06_cat_15',
 'ps_car_06_cat_16',
 'ps_car_06_cat_17',
 'ps_car_08_cat_0',
 'ps_car_08_cat_1',
 'ps_car_11_cat_1',
 'ps_car_11_cat_2',
 'ps_car_11_cat_3',
 'ps_car_11_cat_4',
 'ps_car_11_cat_5',
 'ps_car_11_cat_6',
 'ps_car_11_cat_7',
 'ps_car_11_cat_8',
 'ps_car_11_cat_9',
 'ps_car_11_cat_10',
 'ps_car_11_cat_11',
 'ps_car_11_cat_12',
 'ps_car_11_cat_13',
 'ps_car_11_cat_14',
 'ps_car_11_cat_15',
 'ps_car_11_cat_16',
 'ps_car_11_cat_17',
 'ps_car_11_cat_18',
 'ps_car_11_cat_19',
 'ps_car_11_cat_20',
 'ps_car_11_cat_21',
 'ps_car_11_cat_22',
 'ps_car_11_cat_23',
 'ps_car_11_cat_24',
 'ps_car_11_cat_25',
 'ps_car_11_cat_26',
 'ps_car_11_cat_27',
 'ps_car_11_cat_28',
 'ps_car_11_cat_29',
 'ps_car_11_cat_30',
 'ps_car_11_cat_31',
 'ps_car_11_cat_32',
 'ps_car_11_cat_33',
 'ps_car_11_cat_34',
 'ps_car_11_cat_35',
 'ps_car_11_cat_36',
 'ps_car_11_cat_37',
 'ps_car_11_cat_38',
 'ps_car_11_cat_39',
 'ps_car_11_cat_40',
 'ps_car_11_cat_41',
 'ps_car_11_cat_42',
 'ps_car_11_cat_43',
 'ps_car_11_cat_44',
 'ps_car_11_cat_45',
 'ps_car_11_cat_46',
 'ps_car_11_cat_47',
 'ps_car_11_cat_48',
 'ps_car_11_cat_49',
 'ps_car_11_cat_50',
 'ps_car_11_cat_51',
 'ps_car_11_cat_52',
 'ps_car_11_cat_53',
 'ps_car_11_cat_54',
 'ps_car_11_cat_55',
 'ps_car_11_cat_56',
 'ps_car_11_cat_57',
 'ps_car_11_cat_58',
 'ps_car_11_cat_59',
 'ps_car_11_cat_60',
 'ps_car_11_cat_61',
 'ps_car_11_cat_62',
 'ps_car_11_cat_63',
 'ps_car_11_cat_64',
 'ps_car_11_cat_65',
 'ps_car_11_cat_66',
 'ps_car_11_cat_67',
 'ps_car_11_cat_68',
 'ps_car_11_cat_69',
 'ps_car_11_cat_70',
 'ps_car_11_cat_71',
 'ps_car_11_cat_72',
 'ps_car_11_cat_73',
 'ps_car_11_cat_74',
 'ps_car_11_cat_75',
 'ps_car_11_cat_76',
 'ps_car_11_cat_77',
 'ps_car_11_cat_78',
 'ps_car_11_cat_79',
 'ps_car_11_cat_80',
 'ps_car_11_cat_81',
 'ps_car_11_cat_82',
 'ps_car_11_cat_83',
 'ps_car_11_cat_84',
 'ps_car_11_cat_85',
 'ps_car_11_cat_86',
 'ps_car_11_cat_87',
 'ps_car_11_cat_88',
 'ps_car_11_cat_89',
 'ps_car_11_cat_90',
 'ps_car_11_cat_91',
 'ps_car_11_cat_92',
 'ps_car_11_cat_93',
 'ps_car_11_cat_94',
 'ps_car_11_cat_95',
 'ps_car_11_cat_96',
 'ps_car_11_cat_97',
 'ps_car_11_cat_98',
 'ps_car_11_cat_99',
 'ps_car_11_cat_100',
 'ps_car_11_cat_101',
 'ps_car_11_cat_102',
 'ps_car_11_cat_103',
 'ps_car_11_cat_104',
 'ps_car_15_0.0',
 'ps_car_15_1.0',
 'ps_car_15_1.4142135624',
 'ps_car_15_1.7320508076',
 'ps_car_15_2.0',
 'ps_car_15_2.2360679775',
 'ps_car_15_2.4494897428',
 'ps_car_15_2.6457513111',
 'ps_car_15_2.8284271247',
 'ps_car_15_3.0',
 'ps_car_15_3.1622776602',
 'ps_car_15_3.3166247904',
 'ps_car_15_3.4641016151',
 'ps_car_15_3.6055512755',
 'ps_car_15_3.7416573868']

I'll gonna make four models. Logistic regression, random forest, LGBM and CNN. Since 186 is 6 * 31, we may can regard train data as 6 * 31 size picture in CNN.

# Logistic Regression

In [0]:
train = train.dropna()

In [0]:
# log-reg first

from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

test_log = test['target']
model = LinearRegression()
model.fit(train[var_list], train['target'])
test_log = model.predict(test[var_list])
print(r2_score(train['target'], model.predict(train[var_list]).round()))

-0.037826254496379885

In [0]:
test_log = pd.concat([test['id'], pd.DataFrame(test_log)], axis = 1)
test_log = test_log.rename(columns = {0: "target"}) 
test_log.to_csv('logistic_pred2.csv', index = False)

0.23................

# Random Forest

In [0]:
from sklearn.ensemble import RandomForestRegressor

test_ran = test[['id', 'target']]
model = RandomForestRegressor(n_estimators=200, max_depth=10)
model.fit(train[var_list], train['target'])
test_ran['target'] = model.predict(test[var_list])
print(r2_score(train['target'], model.predict(train[var_list]).round()))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

-0.03682162873144845

In [0]:
test_ran.head()

   id    target
0   0  0.031409
1   1  0.024993
2   2  0.034547
3   3  0.019440
4   4  0.037282

In [0]:
test_ran.to_csv('random_pred2.csv', index = False)

I got 0.250.

# LGBM

In [0]:
import lightgbm as lgb
params = {}
params['learning_rate'] = 0.01
params['boosting_type'] = 'gbdt'
params['objective'] = 'binary'
params['metric'] = 'binary_logloss'
params['sub_feature'] = 0.9
params['num_leaves'] = 50
params['min_data'] = 50
params['max_depth'] = 10

test_lgbm = test[['id', 'target']]
d_train = lgb.Dataset(train[var_list], label=train['target'])
model = lgb.train(params, d_train, 200)
test_lgbm['target'] = model.predict(test[var_list])
print(r2_score(train['target'], model.predict(train[var_list]).round()))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

-0.037826254496379885

In [0]:
test_lgbm.head()

   id    target
0   0  0.034560
1   1  0.027395
2   2  0.031117
3   3  0.020019
4   4  0.039535

In [0]:
test_lgbm.to_csv('lgbm_pred2.csv', index = False)

0.256.